ALTER TYPE "QuestionKind" ADD VALUE IF NOT EXISTS 'TRUE_FALSE';
ALTER TYPE "QuestionKind" ADD VALUE IF NOT EXISTS 'SHORT_ANSWER';
ALTER TYPE "QuestionKind" ADD VALUE IF NOT EXISTS 'MATCHING';

ALTER TABLE "attempt_answers"
ADD COLUMN IF NOT EXISTS "selected_option_ids" JSONB,
ADD COLUMN IF NOT EXISTS "answer_text" TEXT;
